### ISSUE TITLE
Can't find description for what options.to_a is supposed to return

### ISSUE THREAD

**Issue by Chuckv** [watir/watirspec#31]
maybe I'm just not looking in the right place, but I can't find anything for what .to_a is supposed to do when used against an OptionCollection object.   I see it in the rspec but nothing under the spec for collections or select_list..  is it hiding somewhere else? 

is this going to return just the text, or an array of hashes or what?

**Comment by p0deje** [comment]
OptionCollection is nothing different from other collections. Calling `#to_a` on it will return an array of `Watir::Option` instances matching selector.

We're missing specs for it, indeed. I believe whenever we start using `shared_examples` for element/collection specs this will be automatically resolved.
