### ISSUE TITLE
EADDRNOTAVAIL exceptions

### ISSUE THREAD

**Issue by titusfortner** [watir/watirspec#56]
While running watirspec with Chrome, toward the end of the run, everything starts giving this error.

It isn't always starting on the same test, and it isn't always the same wire call. I haven't had any issues with Firefox. Is this a Chrome bug? (I think my system just updated Chrome today). Any ideas what I can do to fix this, regardless? 

Errno::EADDRNOTAVAIL: Cannot assign requested address - connect(2) for "127.0.0.1" port 9516
/home/titus/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:879:in `initialize'
/home/titus/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:879:in `open'
/home/titus/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
/home/titus/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
/home/titus/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:878:in `connect'
/home/titus/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
/home/titus/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:852:in `start'

**Comment by jarib** [comment]
Doesn't sound Chrome-related to me. Do you see the same thing with an older Ruby?

**Comment by jarib** [comment]
Also the full stacktrace would be useful.

**Comment by jarib** [comment]
I'm not sure what kind of load this machine is running under, but you're probably hitting the max number of [ephemeral ports](https://en.wikipedia.org/wiki/Ephemeral_port) the OS can use for outgoing connections. 

On Linux, you can tweak this number through the `net.ipv4.ip_local_port_range` kernel setting. You can  `cat /proc/sys/net/ipv4/ip_local_port_range` to see the current range.

In any case it's not a watirspec issue, so I'm closing this.

**Comment by titusfortner** [comment]
Yes, I'm on latest Linux Mint. ip_local_port_range is 32768 61000, so I don't see how I'd be hitting the max number, especially if I'm running the tests on a clean/just-rebooted system. I'll try running with a previous version of Ruby and see if that makes a difference. Thanks.
