### ISSUE TITLE
Future of Watirspec

### ISSUE THREAD

**Issue by titusfortner** [watir/watirspec#81]
I stated at the Bazaar that I'd like to see this repo merged in with the existing WebDriver code, since that is the only code base that is currently testable by this repo. The point was made that we'd like Watir to have options to be extensible by code in other repos, which could only be tested if Watirspec remained separate.

I propose:
 1. Remove guards for :watir_classic
 2. Remove need to specify :webdriver in guards
 3. Move current watir-webdriver repo specs into watirspec so that all tests currently applicable to watir are in one place.

I'd also love to see Watir & Ruby Selenium specs run with the same test implementations (same setup, same server implementation and guard structures, etc), but we can talk about that possibility later.

**Comment by p0deje** [comment]
1. Let's do that.
2. Let's do that.

I was sure we decided to actually keep watirspec in separate repo so that it can be used to test various extensions when we allow them (like watizzle) , didn't we?

**Comment by titusfortner** [comment]
yup, just wanted to make sure we were on the same page before I worked on this - https://github.com/watir/watirspec/pull/82
